### ISSUE TITLE
Extra buttons in dialogs

### ISSUE THREAD

**Issue by fjmm** [newghost/bootstrap-jquery-plugin#16]
There seems to be an issue with extra buttons in a dialog. The problem happens when you add a function to the array prototype, the name of the new function appears as a new button in the dialog.

Array.prototype.whatever = function() {};

$("#dialog").dialog({
    buttons: [
        { text: "1" },
        { text: "2" }
    ]
});

Looking at the code the problem seems to be related to lines 69 and 70(I believe): 
"for (var button in buttons) {
var btnObj = buttons[button]".

Replacing the lines above with the ones below should take care of the problem
"for (var i=0, x=buttons.length;i<x; i++) {
var btnObj = buttons[i]"

**Comment by newghost** [comment]
Thank you for reporting this, the buttons maybe an object, i.e:

      $("#dialog").dialog({ 'ok': function() {} });

I use another method to resolve this, you can have a try.
