### ISSUE TITLE
不知道是不是dialog中的一个bug

### ISSUE THREAD

**Issue by Jin-Huiming** [newghost/bootstrap-jquery-plugin#18]
用下载的新代码，可以了！

**Comment by Jin-Huiming** [comment]
问题依然有，
<script>
//show dialog
$("#ChoiceForm").dialog({});
//如果不事先执行带有options的语句,下面的语句不显示
$("#ChoiceForm").dialog("open");
</script>

**Comment by newghost** [comment]
什么BUG?

**Comment by Jin-Huiming** [comment]
<section id="dialog">
        <div class="hide">
            <div id="ChoiceForm">
                <label for="search">找</label>
                <input class="form-control" type="text" id="search" />
                <div id="datagrid"></div>
                <p>这里是要显示的内容！</p>
            </div>
        </div>
    </section>
//直接用下面的语句,不能显示dialog
 $("#ChoiceForm").dialog("open");
//下面的语句可以，而且执行下面的语句后，再执行上面的语句，也可以打开
 $("#ChoiceForm").dialog({title:"选择服务商"});

**Comment by newghost** [comment]
不应该不算BUG， Dialog需要先初始化才能被打开 
$("#ChoiceForm").dialog(options);
$("#ChoiceForm").dialog("open");


参照了jQuery UI的设计
